[package]
name = "navfs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.27.0"
itertools = "0.13.0"
ratatui = "0.26.3"
users = "0.11.0"
argmap = "1.1.2"
indoc = "2.0.5"
rascii_art = "0.4.5"
ansi-to-tui = "7.0.0"
